import { Card } from "@/components/ui/Card";
import { CONTACT_EMAIL, LEGAL_LAST_UPDATED } from "@/lib/siteConfig";

export const metadata = { title: "Terms of Service — Skywatch VB" };

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6">
      <h1 className="text-3xl font-bold text-ocean-800 dark:text-sand-50">Terms of Service</h1>
      <p className="mt-2 text-sm text-ocean-600 dark:text-ocean-200">
        Last updated: {LEGAL_LAST_UPDATED} — Draft. Have a local attorney review this
        before launch; it is not legal advice.
      </p>

      <Card className="mt-6 space-y-5 text-ocean-700 dark:text-sand-100">
        <section>
          <h2 className="text-lg font-bold text-ocean-800 dark:text-sand-50">
            Not an emergency service
          </h2>
          <p className="mt-1">
            Skywatch VB is a community information resource, not an official emergency
            or forecasting service. For life-threatening emergencies, call 911. For
            official flood forecasts, warnings, and evacuation guidance, always follow
            the National Weather Service and the City of Virginia Beach / Virginia
            Department of Emergency Management — not this site.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-ocean-800 dark:text-sand-50">
            Flood risk information is an estimate
          </h2>
          <p className="mt-1">
            The flood risk levels shown on this site are generated by a heuristic we
            built from public NOAA and National Weather Service data. It is not an
            official flood forecast, is not reviewed by a hydrologist or emergency
            manager, and can be wrong. Do not use it as your sole basis for
            life-safety decisions.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-ocean-800 dark:text-sand-50">
            Alerts aren&apos;t guaranteed
          </h2>
          <p className="mt-1">
            Email and text alerts depend on third-party delivery services, your device,
            and your network — they can be delayed or fail to arrive. Don&apos;t rely on
            a Skywatch VB alert as your only source of warning during severe weather.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-ocean-800 dark:text-sand-50">
            Your account
          </h2>
          <p className="mt-1">
            You&apos;re responsible for the accuracy of the address and contact info you
            provide, and for keeping your login credentials secure. We may suspend
            accounts used to abuse the service (for example, submitting false flood
            reports once that feature launches).
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-ocean-800 dark:text-sand-50">
            No warranty, limited liability
          </h2>
          <p className="mt-1">
            Skywatch VB is provided &quot;as is,&quot; without warranties of any kind.
            To the fullest extent permitted by law, we aren&apos;t liable for damages
            arising from your use of, or inability to use, this site or its data.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-ocean-800 dark:text-sand-50">Changes</h2>
          <p className="mt-1">
            We may update these terms as the site grows. Material changes will be
            noted on this page.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-ocean-800 dark:text-sand-50">Contact</h2>
          <p className="mt-1">
            Questions:{" "}
            <a href={`mailto:${CONTACT_EMAIL}`} className="underline">
              {CONTACT_EMAIL}
            </a>
            .
          </p>
        </section>
      </Card>
    </div>
  );
}
